version: "3.8"

services:
  scanner:
    container_name: fujitsu_scanner
    image: fujitsu_scanner
#    build: .
    restart: "always"
    privileged: true
    volumes:
      - /data/MetsDocs/OneDrive/dustin/ScanSnap:/scans
#      - /mnt/user/appdata/paperless-ngx/data/consume:/scans
      - /var/run/dbus:/var/run/dbus
